add solution for module 5 template
js-tasks-ru/htmlcss-20210513_comradchegm pull request #13
Opened 2021-05-31 05:13 UTC by AndreyComanche

2021-05-31 05:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-01 09:40 UTC, GSemikozov requested changes

2021-06-01 09:40 UTC, GSemikozov commented on components/template/footer.css
> +    background-color: blueviolet;
ой, не стоит задавать цвета как в примере на лекции - мы ориентируемся прежде всего на макет в фигме)

2021-06-01 09:40 UTC, GSemikozov commented on components/template/header.css
> +    background-color: aqua;
и тут тоже

2021-06-01 09:40 UTC, GSemikozov commented on components/template/main.css
> +    background-color: chartreuse;
и тут

2021-06-01 09:40 UTC, GSemikozov commented on components/template/main.css
> +    background-color: chartreuse;
и ниже тоже

2021-06-01 09:40 UTC, GSemikozov commented on components/template/template.css
> +html, body {
вот эту часть (общие стили через селекторы тегов) можно прямо в тег style в html решения

2021-06-01 10:07 UTC, AndreyComanche commented on components/template/footer.css
> +    background-color: blueviolet;
Цвета поправил

2021-06-01 10:07 UTC, AndreyComanche commented on components/template/header.css
> +    background-color: aqua;
Цвета поправил

2021-06-01 10:07 UTC, AndreyComanche commented on components/template/main.css
> +    background-color: chartreuse;
Цвета поправил

2021-06-01 10:07 UTC, AndreyComanche commented on components/template/template.css
> +html, body {
Перенес.

2021-06-01 10:54 UTC, GSemikozov approved these changes

2021-06-01 10:54 UTC, merged