Radio
js-tasks-ru/htmlcss-20210513_comradchegm pull request #22
Opened 2021-06-05 12:32 UTC by AndreyComanche

2021-06-05 12:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-11 09:16 UTC, GSemikozov requested changes

2021-06-11 09:16 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    position: absolute;
по идее в ПР-е про чекбокс должен был отмечать - здесь еще нужно обнулить outline: none, и скрыть через opacity: 0 (на случай если сторонние стили добавить неявные отступы)

2021-06-11 13:22 UTC, AndreyComanche commented on 07-lection5/02-radio/radio.css
> +    position: absolute;
Исправил

2021-06-12 08:35 UTC, GSemikozov approved these changes

2021-06-12 08:35 UTC, merged